# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

import flatbuffers

class PredictResponse(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsPredictResponse(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = PredictResponse()
        x.Init(buf, n + offset)
        return x

    # PredictResponse
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # PredictResponse
    def MsgIds(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # PredictResponse
    def MsgIdsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # PredictResponse
    def MsgIdsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

def PredictResponseStart(builder): builder.StartObject(1)
def PredictResponseAddMsgIds(builder, msgIds): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(msgIds), 0)
def PredictResponseStartMsgIdsVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def PredictResponseEnd(builder): return builder.EndObject()
