# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

import flatbuffers

class PredictRequest(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsPredictRequest(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = PredictRequest()
        x.Init(buf, n + offset)
        return x

    # PredictRequest
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # PredictRequest
    def Inputs(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from FloatsInput import FloatsInput
            obj = FloatsInput()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # PredictRequest
    def InputsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # PredictRequest
    def MsgIds(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # PredictRequest
    def MsgIdsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # PredictRequest
    def MsgIdsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

def PredictRequestStart(builder): builder.StartObject(2)
def PredictRequestAddInputs(builder, inputs): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(inputs), 0)
def PredictRequestStartInputsVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def PredictRequestAddMsgIds(builder, msgIds): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(msgIds), 0)
def PredictRequestStartMsgIdsVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def PredictRequestEnd(builder): return builder.EndObject()
