# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc
import flatbuffers

builder = flatbuffers.Builder(0)

class PredictStub(object):
  
  def __init__(self, channel):
    """Constructor.
    
    Args:
      channel: A grpc.Channel.
    """
    self.PredictFloats = channel.unary_unary(
        '/Predict/PredictFloats',
        
        
        )


class PredictServicer(object):
  
  def PredictFloats(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_PredictServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'PredictFloats': grpc.unary_unary_rpc_method_handler(
          servicer.PredictFloats,
          
          
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Predict', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities
  import flatbuffers
  
  builder = flatbuffers.Builder(0)  
  
  class PredictStub(object):
    
    def __init__(self, channel):
      """Constructor.
      
      Args:
        channel: A grpc.Channel.
      """
      self.PredictFloats = channel.unary_unary(
          '/Predict/PredictFloats',
          
          
          )
  
  
  class PredictServicer(object):
    
    def PredictFloats(self, request, context):
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')
  
  
  def add_PredictServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'PredictFloats': grpc.unary_unary_rpc_method_handler(
            servicer.PredictFloats,
            
            
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'Predict', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
  
  
  class BetaPredictServicer(object):
    """The Beta API is deprecated for 0.15.0 and later.
    
    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    def PredictFloats(self, request, context):
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)
  
  
  class BetaPredictStub(object):
    """The Beta API is deprecated for 0.15.0 and later.
    
    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    def PredictFloats(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      raise NotImplementedError()
    PredictFloats.future = None
  
  
  def beta_create_Predict_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
    """The Beta API is deprecated for 0.15.0 and later.
    
    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    method_implementations = {
      ('Predict', 'PredictFloats'): face_utilities.unary_unary_inline(servicer.PredictFloats),
    }
    server_options = beta_implementations.server_options(thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
    return beta_implementations.server(method_implementations, options=server_options)
  
  
  def beta_create_Predict_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
    """The Beta API is deprecated for 0.15.0 and later.
    
    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    cardinalities = {
      'PredictFloats': cardinality.Cardinality.UNARY_UNARY,
    }
    stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, thread_pool=pool, thread_pool_size=pool_size)
    return beta_implementations.dynamic_stub(channel, 'Predict', cardinalities, options=stub_options)
except ImportError:
  pass