# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import spd_frontend_pb2 as spd__frontend__pb2


class PredictStub(object):
  """A prediction server
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.PredictFloats = channel.unary_unary(
        '/clipper.grpc.Predict/PredictFloats',
        request_serializer=spd__frontend__pb2.PredictRequest.SerializeToString,
        response_deserializer=spd__frontend__pb2.PredictResponse.FromString,
        )


class PredictServicer(object):
  """A prediction server
  """

  def PredictFloats(self, request, context):
    """Method to send a prediction request with float data
    and receive a response
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_PredictServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'PredictFloats': grpc.unary_unary_rpc_method_handler(
          servicer.PredictFloats,
          request_deserializer=spd__frontend__pb2.PredictRequest.FromString,
          response_serializer=spd__frontend__pb2.PredictResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'clipper.grpc.Predict', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
